# Generated by Django 2.0.5 on 2018-05-31 09:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_path', models.CharField(default='?', max_length=500)),
                ('status', models.IntegerField(default=0, max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('initial_salary', models.IntegerField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='hr',
            fields=[
                ('hr_id', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback', models.CharField(default='?', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='interviewee',
            fields=[
                ('ee_id', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='interviewer',
            fields=[
                ('er_id', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='play',
            fields=[
                ('play_id', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('ee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.interviewee')),
                ('er_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.interviewer')),
                ('hr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.hr')),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('position_id', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('job', models.CharField(default='?', max_length=50)),
                ('location', models.CharField(default='?', max_length=50)),
                ('excepted_salary', models.CharField(default='?', max_length=10)),
                ('job_description', models.CharField(default='?', max_length=500)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.hr')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users'),
        ),
        migrations.AddField(
            model_name='interview',
            name='ee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.interviewee'),
        ),
        migrations.AddField(
            model_name='interview',
            name='er_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.interviewer'),
        ),
        migrations.AddField(
            model_name='apply',
            name='ee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.interviewee'),
        ),
        migrations.AddField(
            model_name='apply',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.position'),
        ),
    ]
