# Generated by Django 2.0.5 on 2018-06-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180602_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='hr_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.hr'),
        ),
    ]
