# Generated by Django 2.0.5 on 2018-06-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_interview_hr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='hr_id',
        ),
    ]
